version: "3"

services:
  app:
    build: .docker
    ports:
      - '80:80'
    depends_on:
      - db
      - node
    volumes:
      - .:/var/www
      - ./public/.htaccess.docker:/var/www/public/.htaccess

  db:
    image: mariadb:10.3
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=laeubrary
      - MYSQL_ROOT_PASSWORD=will-be-randomized-and-output-on-the-console
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=laeubrary
      - MYSQL_PASSWORD=laeubrary

  node:
    image: node:14
    working_dir: '/app'
    volumes:
      - .:/app
    command: bash -c "npm install && npm run watch"

  mail:
    image: schickling/mailcatcher:latest
    ports:
      - '1080:1080'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - '8081:80'

  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
